[package]
name = "weather_visualizer"
version = "0.1.0"
edition = "2021"

[dependencies]
nannou = "0.18.0"
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde_json = "1.0"
dotenvy = "0.15"
